'use client';

import { useEffect, useState, useRef } from 'react';
import { createClient } from '@supabase/supabase-js';
import { HeartPulse, RefreshCw, AlertTriangle, CheckCircle2, Phone, FileDown, Activity, Search, X, TrendingUp, Calendar, ChevronDown, ChevronUp, Users, Sparkles, Loader2, Info, Mail } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  Legend,
  ResponsiveContainer,
} from 'recharts';

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
);

export default function Dashboard() {
  const [reports, setReports] = useState<any[]>([]);
  const [isRefreshing, setIsRefreshing] = useState(false);
  const [filter, setFilter] = useState<'all' | 'critical' | 'normal'>('all');
  const [searchTerm, setSearchTerm] = useState('');
  const [chartAnimation, setChartAnimation] = useState(false);
  const [showFullGraph, setShowFullGraph] = useState(false);
  const [selectedPerson, setSelectedPerson] = useState<'father' | 'mother'>('father');
  const [isSummarizing, setIsSummarizing] = useState(false);
  const [aiSummary, setAiSummary] = useState<string | null>(null);
  const [showSummary, setShowSummary] = useState(false);
  const [showDatePickerModal, setShowDatePickerModal] = useState(false);
  const [startDate, setStartDate] = useState<string>('');
  const [endDate, setEndDate] = useState<string>('');
  const [lastUpdated, setLastUpdated] = useState<string>('');
  const [isExporting, setIsExporting] = useState(false);
  const [isMounted, setIsMounted] = useState(false);
  const [showEmailModal, setShowEmailModal] = useState(false);
  const [emailTo, setEmailTo] = useState('doctor@clinic.com');
  const [emailFrom, setEmailFrom] = useState('nri.child@example.com');
  const dashboardRef = useRef<HTMLDivElement>(null);
  const printContentRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    setIsMounted(true);
    setLastUpdated(new Date().toLocaleString());
  }, []);

  const fetchData = async () => {
    setIsRefreshing(true);
    const { data, error } = await supabase
      .schema('public')
      .from('Report')
      .select('*')
      .order('createdAt', { ascending: true });

    if (!error) {
      setReports(data || []);
      setLastUpdated(new Date().toLocaleString());
    }
    setIsRefreshing(false);
  };

  useEffect(() => {
    fetchData();
    const channel = supabase.channel('reports_channel')
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'Report' },
        (payload) => {
          setReports((prev) => [...prev, payload.new]);
          setLastUpdated(new Date().toLocaleString());
        })
      .subscribe();
    return () => { supabase.removeChannel(channel); };
  }, []);

  useEffect(() => {
    if (chartData.length > 0) {
      setChartAnimation(true);
      const timer = setTimeout(() => setChartAnimation(false), 500);
      return () => clearTimeout(timer);
    }
  }, [filter, selectedPerson, reports.length]);

  const sendEmailToDoctor = () => {
    const subject = `Health Summary for ${selectedPerson === 'father' ? 'Father' : 'Mother'} - Dear Comrade`;
    const body = `
Dear Doctor,

Please find below the AI-generated health summary for my ${selectedPerson === 'father' ? 'father' : 'mother'}:

${aiSummary}

---
Generated by Dear Comrade - Clinical Care Coordination for NRI Families
Date: ${new Date().toLocaleString()}
  `;

    const gmailComposeUrl = `https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(emailTo)}&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;

    window.open(gmailComposeUrl, '_blank');
    setShowEmailModal(false);
  };

  const exportToPDF = async () => {
    setIsExporting(true);

    const originalContent = document.body.cloneNode(true) as HTMLElement;

    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('Please allow pop-ups to generate PDF');
      setIsExporting(false);
      return;
    }

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>Dear Comrade - Health Report</title>
        <meta charset="utf-8">
        <style>
          * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
          }
          body {
            font-family: system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', sans-serif;
            padding: 40px;
            background: white;
            color: #0f172a;
          }
          .print-container {
            max-width: 1200px;
            margin: 0 auto;
          }
          .header {
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 20px;
            border-bottom: 2px solid #e2e8f0;
          }
          .header h1 {
            font-size: 24px;
            font-weight: bold;
            display: flex;
            align-items: center;
            justify-content: center;
            gap: 8px;
            margin-bottom: 8px;
          }
          .header p {
            color: #64748b;
            font-size: 12px;
          }
          .stats-grid {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            gap: 16px;
            margin-bottom: 24px;
          }
          .stat-card {
            border: 1px solid #e2e8f0;
            border-radius: 12px;
            padding: 16px;
            background: white;
          }
          .stat-title {
            font-size: 10px;
            font-weight: bold;
            text-transform: uppercase;
            color: #94a3b8;
            margin-bottom: 4px;
          }
          .stat-value {
            font-size: 24px;
            font-weight: bold;
            color: #0f172a;
          }
          .chart-container {
            border: 1px solid #e2e8f0;
            border-radius: 12px;
            padding: 16px;
            margin-bottom: 24px;
          }
          .chart-title {
            font-size: 14px;
            font-weight: bold;
            margin-bottom: 16px;
            color: #0f172a;
          }
          .reports-section {
            margin-top: 24px;
          }
          .reports-title {
            font-size: 14px;
            font-weight: bold;
            margin-bottom: 12px;
            color: #0f172a;
          }
          .report-item {
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            padding: 12px;
            margin-bottom: 12px;
            page-break-inside: avoid;
          }
          .report-badge {
            display: inline-block;
            padding: 2px 8px;
            border-radius: 12px;
            font-size: 9px;
            font-weight: bold;
            margin-right: 8px;
          }
          .badge-critical {
            background: #dc2626;
            color: white;
          }
          .badge-normal {
            background: #e2e8f0;
            color: #475569;
          }
          .report-date {
            font-size: 9px;
            color: #94a3b8;
          }
          .report-summary {
            font-size: 11px;
            color: #334155;
            margin-top: 8px;
            line-height: 1.5;
          }
          .footer {
            margin-top: 30px;
            padding-top: 16px;
            border-top: 1px solid #e2e8f0;
            text-align: center;
            font-size: 9px;
            color: #94a3b8;
          }
          @media print {
            body {
              padding: 20px;
            }
            .page-break {
              page-break-before: always;
            }
          }
        </style>
      </head>
      <body>
        <div class="print-container">
    `);

    printWindow.document.write(`
  <div class="header">
    <h1>❤️ Dear Comrade</h1>
    <p>Keeping you close, even when you're far away</p>
    <div style="margin-top: 8px; padding: 4px 12px; background: ${selectedPerson === 'father' ? '#dbeafe' : '#fce7f3'}; border-radius: 20px; display: inline-block;">
      <span style="font-size: 12px; font-weight: 600; color: ${selectedPerson === 'father' ? '#1e40af' : '#be185d'};">📋 Report for: ${selectedPerson === 'father' ? 'Father' : 'Mother'}</span>
    </div>
  </div>
`);

    printWindow.document.write(`
      <div class="stats-grid">
        <div class="stat-card">
          <div class="stat-title">${selectedPerson === 'father' ? 'Father' : 'Mother'}'s Reports</div>
          <div class="stat-value">${personFilteredReports.length}</div>
        </div>
        <div class="stat-card">
          <div class="stat-title">Critical Alerts</div>
          <div class="stat-value" style="color: ${criticalCount > 0 ? '#dc2626' : '#0f172a'}">${criticalCount}</div>
        </div>
        <div class="stat-card">
          <div class="stat-title">Normal Reports</div>
          <div class="stat-value">${normalCount}</div>
        </div>
        <div class="stat-card">
          <div class="stat-title">All Reports</div>
          <div class="stat-value">${personFilteredReports.length}</div>
        </div>
      </div>
    `);

    if (chartData.length > 0) {
      printWindow.document.write(`
        <div class="chart-container">
          <div class="chart-title">📊 ${getChartTitle()}</div>
          <table style="width: 100%; border-collapse: collapse; font-size: 11px;">
            <thead>
              <tr><th style="text-align: left; padding: 8px; border-bottom: 1px solid #e2e8f0;">Date</th>
                <th style="text-align: right; padding: 8px; border-bottom: 1px solid #e2e8f0;">Critical</th>
                <th style="text-align: right; padding: 8px; border-bottom: 1px solid #e2e8f0;">Normal</th>
                <th style="text-align: right; padding: 8px; border-bottom: 1px solid #e2e8f0;">Total</th>
              </tr>
            </thead>
            <tbody>
      `);
      chartData.forEach((data: any) => {
        printWindow.document.write(`
          <tr>
            <td style="padding: 8px; border-bottom: 1px solid #f1f5f9;">${data.date}</td>
            <td style="padding: 8px; text-align: right; border-bottom: 1px solid #f1f5f9;">${data.critical}</td>
            <td style="padding: 8px; text-align: right; border-bottom: 1px solid #f1f5f9;">${data.normal}</td>
            <td style="padding: 8px; text-align: right; border-bottom: 1px solid #f1f5f9;">${data.total}</td>
          </tr>
        `);
      });
      printWindow.document.write(`
            </tbody>
          </table>
        </div>
      `);
    }

    printWindow.document.write(`
      <div class="reports-section">
        <div class="reports-title">📋 All Reports (${filteredReports.length})</div>
    `);

    filteredReports.forEach((report) => {
      printWindow.document.write(`
        <div class="report-item">
          <div>
            <span class="report-badge ${report.isCritical ? 'badge-critical' : 'badge-normal'}">${report.isCritical ? 'CRITICAL' : 'NORMAL'}</span>
            <span class="report-date">${new Date(report.createdAt).toLocaleString()}</span>
          </div>
          <div class="report-summary">${report.summary}</div>
        </div>
      `);
    });

    printWindow.document.write(`
      </div>
      <div class="footer">
        Generated on ${new Date().toLocaleString()} | Dear Comrade - Clinical Care Coordination for NRI Families
      </div>
    `);

    printWindow.document.write(`
        </div>
      </body>
      </html>
    `);

    printWindow.document.close();

    printWindow.onload = () => {
      setTimeout(() => {
        printWindow.print();
        printWindow.onafterprint = () => {
          printWindow.close();
        };
        setIsExporting(false);
      }, 500);
    };
  };

  const personFilteredReports = reports;

  const criticalCount = personFilteredReports.filter(r => r.isCritical).length;
  const normalCount = personFilteredReports.filter(r => !r.isCritical).length;

  const theme = {
    father: {
      bg: 'bg-gradient-to-br from-blue-50 via-white to-blue-50',
      cardBg: 'bg-white/80',
      border: 'border-blue-200',
      text: 'text-blue-700',
      buttonBg: 'bg-blue-600',
      buttonHover: 'hover:bg-blue-700',
      toggleActive: 'bg-blue-600',
      toggleInactive: 'text-blue-600 hover:bg-blue-50',
      accentLight: 'bg-blue-100',
      accentDark: 'bg-blue-600',
      heartColor: 'text-blue-500',
      gradient: 'from-blue-500 to-blue-600',
    },
    mother: {
      bg: 'bg-gradient-to-br from-pink-50 via-white to-pink-50',
      cardBg: 'bg-white/80',
      border: 'border-pink-200',
      text: 'text-pink-700',
      buttonBg: 'bg-pink-600',
      buttonHover: 'hover:bg-pink-700',
      toggleActive: 'bg-pink-600',
      toggleInactive: 'text-pink-600 hover:bg-pink-50',
      accentLight: 'bg-pink-100',
      accentDark: 'bg-pink-600',
      heartColor: 'text-pink-500',
      gradient: 'from-pink-500 to-pink-600',
    }
  };

  const currentTheme = selectedPerson === 'father' ? theme.father : theme.mother;

  const isDateInRange = (reportDate: Date, startDateStr: string, endDateStr: string) => {
    const reportDateOnly = new Date(reportDate);
    reportDateOnly.setHours(0, 0, 0, 0);

    if (startDateStr && endDateStr) {
      const start = new Date(startDateStr);
      start.setHours(0, 0, 0, 0);
      const end = new Date(endDateStr);
      end.setHours(23, 59, 59, 999);
      return reportDateOnly >= start && reportDateOnly <= end;
    } else if (startDateStr) {
      const start = new Date(startDateStr);
      start.setHours(0, 0, 0, 0);
      return reportDateOnly >= start;
    } else if (endDateStr) {
      const end = new Date(endDateStr);
      end.setHours(23, 59, 59, 999);
      return reportDateOnly <= end;
    }
    return true;
  };

  const getReportsByDateRange = () => {
    if (!startDate && !endDate) return personFilteredReports;
    return personFilteredReports.filter(report => {
      const reportDate = new Date(report.createdAt);
      return isDateInRange(reportDate, startDate, endDate);
    });
  };

  const openDatePicker = () => {
    setShowDatePickerModal(true);
  };

  const generateAISummary = async () => {
    setIsSummarizing(true);
    setShowDatePickerModal(false);

    try {
      const reportsToSummarize = getReportsByDateRange();

      if (reportsToSummarize.length === 0) {
        const dateRangeText = startDate && endDate
          ? `${new Date(startDate).toLocaleDateString()} to ${new Date(endDate).toLocaleDateString()}`
          : startDate
            ? `from ${new Date(startDate).toLocaleDateString()}`
            : endDate
              ? `up to ${new Date(endDate).toLocaleDateString()}`
              : "all time";

        setAiSummary(`No health reports found for ${selectedPerson === 'father' ? 'your father' : 'your mother'} in the selected date range (${dateRangeText}).\n\nAvailable reports in database:\n${personFilteredReports.map(r => `- ${new Date(r.createdAt).toLocaleDateString()}: ${r.isCritical ? '⚠️ Critical' : '✓ Normal'}`).join('\n')}\n\nPlease adjust your date range and try again.`);
        setShowSummary(true);
        setIsSummarizing(false);
        return;
      }

      const reportsData = reportsToSummarize.map(report => ({
        date: new Date(report.createdAt).toLocaleDateString(),
        time: new Date(report.createdAt).toLocaleTimeString(),
        type: report.isCritical ? 'CRITICAL' : 'NORMAL',
        summary: report.summary
      }));

      const dateRangeText = startDate && endDate
        ? `from ${new Date(startDate).toLocaleDateString()} to ${new Date(endDate).toLocaleDateString()}`
        : startDate
          ? `from ${new Date(startDate).toLocaleDateString()} onwards`
          : endDate
            ? `up to ${new Date(endDate).toLocaleDateString()}`
            : "of all time";

      const prompt = `You are a medical assistant for an NRI child monitoring their elderly ${selectedPerson === 'father' ? 'father' : 'mother'}'s health.

Please analyze these health reports ${dateRangeText} (Total: ${reportsToSummarize.length} reports):

${JSON.stringify(reportsData, null, 2)}

Provide a brief, clear English summary covering:
1. Overall health trend during this period (improving/stable/needs attention)
2. Number of critical alerts and their nature
3. Key health observations and patterns
4. Specific recommendations for the family based on this time period

Keep it concise (2-3 paragraphs), empathetic, and actionable. Use ONLY English, no other languages.`;

      const response = await fetch('/api/chat', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          model: 'sarvam-1',
          messages: [
            {
              role: 'system',
              content: 'You are a medical assistant. Always respond in PURE ENGLISH only. Use clear, simple, empathetic English.'
            },
            {
              role: 'user',
              content: prompt
            }
          ],
          temperature: 0.7,
          max_tokens: 800
        })
      });

      if (response.ok) {
        const data = await response.json();
        setAiSummary(data.choices[0].message.content);
      } else {
        setAiSummary(generateMockSummary(reportsToSummarize, selectedPerson, startDate, endDate));
      }
    } catch (error) {
      console.error('Error calling Sarvam AI:', error);
      setAiSummary(generateMockSummary(getReportsByDateRange(), selectedPerson, startDate, endDate));
    } finally {
      setIsSummarizing(false);
      setShowSummary(true);
    }
  };

  const generateMockSummary = (reports: any[], person: string, start?: string, end?: string) => {
    const criticalCount = reports.filter(r => r.isCritical).length;
    const totalReports = reports.length;
    const dateRange = start && end
      ? `${new Date(start).toLocaleDateString()} to ${new Date(end).toLocaleDateString()}`
      : start
        ? `from ${new Date(start).toLocaleDateString()}`
        : end
          ? `up to ${new Date(end).toLocaleDateString()}`
          : "all time";

    if (totalReports === 0) {
      return `No health reports are available for ${person === 'father' ? 'your father' : 'your mother'} in the selected date range (${dateRange}). Please adjust your date range to see more reports.`;
    }

    let summary = `**Health Summary for Your ${person === 'father' ? 'Father' : 'Mother'}**\n\n`;
    summary += `**Period:** ${dateRange}\n`;
    summary += `**Reports Analyzed:** ${totalReports} report${totalReports !== 1 ? 's' : ''}\n\n`;
    summary += `**Report Dates in this period:**\n`;
    const uniqueDates = [...new Set(reports.map(r => new Date(r.createdAt).toLocaleDateString()))].sort();
    summary += uniqueDates.map(d => `• ${d}`).join('\n');
    summary += `\n\n`;

    if (criticalCount > 0) {
      summary += `⚠️ **CRITICAL ALERT:** ${criticalCount} critical issue${criticalCount !== 1 ? 's require' : ' requires'} immediate medical attention!\n\n`;
    }

    summary += `✅ **Overall Health Status:** ${criticalCount === 0 ? 'Stable with no critical issues detected during this period' : 'Requires immediate medical attention'}\n\n`;

    summary += `📋 **Key Observations:**\n`;
    const criticalReports = reports.filter(r => r.isCritical);
    if (criticalReports.length > 0) {
      summary += `• Found ${criticalReports.length} critical alert(s) that need attention\n`;
      criticalReports.forEach((r, idx) => {
        summary += `  ${idx + 1}. ${r.summary}\n`;
      });
    } else {
      summary += `• No critical alerts during this period\n`;
      summary += `• Health appears stable based on ${totalReports} report(s)\n`;
    }
    summary += `\n💡 **Recommendations:**\n`;
    if (criticalCount > 0) {
      summary += `• Schedule a doctor's appointment immediately\n`;
      summary += `• Review critical alerts in detail above\n`;
      summary += `• Contact the family doctor within 24 hours\n`;
    } else {
      summary += `• Continue regular health monitoring\n`;
      summary += `• Maintain current medication and lifestyle routine\n`;
      summary += `• Schedule next routine checkup as recommended\n`;
    }
    summary += `• Keep uploading reports for better health tracking\n\n`;
    summary += `---\n`;
    summary += `*Note: This is an AI-generated summary based on ${totalReports} health report(s) from ${dateRange}. Always consult with healthcare professionals for medical decisions.*`;

    return summary;
  };

  const getChartData = () => {
    const filtered = personFilteredReports.filter(report => {
      if (filter === 'critical' && !report.isCritical) return false;
      if (filter === 'normal' && report.isCritical) return false;
      return true;
    });

    const groupedByDate = new Map();

    filtered.forEach(report => {
      const date = new Date(report.createdAt).toLocaleDateString();
      if (!groupedByDate.has(date)) {
        groupedByDate.set(date, { date, total: 0, critical: 0, normal: 0 });
      }
      const entry = groupedByDate.get(date);
      entry.total++;
      if (report.isCritical) {
        entry.critical++;
      } else {
        entry.normal++;
      }
    });

    return Array.from(groupedByDate.values()).sort((a, b) =>
      new Date(a.date).getTime() - new Date(b.date).getTime()
    );
  };

  const chartData = getChartData();

  const getChartTitle = () => {
    const person = selectedPerson === 'father' ? 'Father' : 'Mother';
    switch (filter) {
      case 'critical': return `${person} - Critical Alerts`;
      case 'normal': return `${person} - Normal Reports`;
      default: return `${person} - Health Reports Overview`;
    }
  };

  const getChartColor = () => {
    switch (filter) {
      case 'critical': return '#ef4444';
      case 'normal': return '#10b981';
      default: return selectedPerson === 'father' ? '#3b82f6' : '#ec4899';
    }
  };

  const filteredReports = personFilteredReports.filter(report => {
    if (filter === 'critical' && !report.isCritical) return false;
    if (filter === 'normal' && report.isCritical) return false;
    if (searchTerm && !report.summary.toLowerCase().includes(searchTerm.toLowerCase())) return false;
    return true;
  }).sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());

  const clearFilters = () => {
    setFilter('all');
    setSearchTerm('');
  };

  if (!isMounted) {
    return null;
  }

  return (
    <div ref={dashboardRef} className={`min-h-screen ${currentTheme.bg} text-slate-900 font-sans antialiased p-4 md:p-6 transition-all duration-500`}>
      <div className="max-w-7xl mx-auto space-y-4">

        <header className="flex flex-col md:flex-row justify-between items-start md:items-center gap-3">
          <div>
            <h1 className="text-xl md:text-2xl font-black text-slate-900 tracking-tight flex items-center gap-2">
              <HeartPulse className={`${currentTheme.heartColor} w-5 h-5 md:w-6 md:h-6 transition-colors duration-300`} /> Dear Comrade
            </h1>
            <p className="text-slate-500 text-xs md:text-sm font-medium">Keeping you close, even when you're far away</p>
          </div>

          <div className="flex items-center gap-3">
            <div className={`flex items-center gap-1 bg-white rounded-lg border ${currentTheme.border} p-1 transition-all duration-300`}>
              <button
                onClick={() => setSelectedPerson('father')}
                className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-xs font-medium transition-all ${selectedPerson === 'father'
                  ? `${currentTheme.buttonBg} text-white shadow-sm`
                  : currentTheme.toggleInactive
                  }`}
              >
                <Users className="w-3 h-3" />
                Father
              </button>
              <button
                onClick={() => setSelectedPerson('mother')}
                className={`flex items-center gap-2 px-3 py-1.5 rounded-md text-xs font-medium transition-all ${selectedPerson === 'mother'
                  ? `${currentTheme.buttonBg} text-white shadow-sm`
                  : currentTheme.toggleInactive
                  }`}
              >
                <Users className="w-3 h-3" />
                Mother
              </button>
            </div>

            <Button
              onClick={openDatePicker}
              className={`flex items-center gap-2 text-xs font-bold px-3 py-1.5 md:px-4 md:py-2 rounded-lg bg-gradient-to-r ${currentTheme.gradient} text-white hover:opacity-90 transition transform hover:scale-105 active:scale-95 shadow-md`}
            >
              <Sparkles className="w-3 h-3 md:w-4 md:h-4" />
              AI Summary
            </Button>

            <Button
              onClick={exportToPDF}
              disabled={isExporting}
              className="flex items-center gap-2 text-xs font-bold px-3 py-1.5 md:px-4 md:py-2 rounded-lg bg-gradient-to-r from-purple-500 to-purple-600 text-white hover:opacity-90 transition transform hover:scale-105 active:scale-95 shadow-md"
            >
              {isExporting ? (
                <Loader2 className="w-3 h-3 md:w-4 md:h-4 animate-spin" />
              ) : (
                <FileDown className="w-3 h-3 md:w-4 md:h-4" />
              )}
              {isExporting ? 'Generating PDF...' : 'Export PDF'}
            </Button>

            <button
              onClick={fetchData}
              className={`flex items-center gap-2 text-xs font-bold px-3 py-1.5 md:px-4 md:py-2 rounded-lg bg-gradient-to-r ${currentTheme.gradient} text-white hover:opacity-90 transition transform hover:scale-105 active:scale-95 shadow-md`}
            >
              <RefreshCw className={`w-3 h-3 md:w-4 md:h-4 ${isRefreshing ? 'animate-spin' : ''}`} /> Sync
            </button>
          </div>
        </header>

        <div className="flex justify-end">
          <div className="flex items-center gap-1.5 text-[10px] text-slate-400 bg-white/50 px-2 py-1 rounded-full">
            <Calendar className="w-2.5 h-2.5" />
            <span suppressHydrationWarning>Last updated: {lastUpdated || 'Loading...'}</span>
          </div>
        </div>

        <Card className="border-amber-200 bg-amber-50/80 shadow-sm">
          <CardContent className="py-0.5 px-4">
            <div className="flex items-center justify-center gap-2">
              <div className="relative">
                <Info className="w-3.5 h-3.5 text-amber-600" />
                <span className="absolute -top-1 -right-1 flex h-2 w-2">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-amber-400 opacity-75"></span>
                  <span className="relative inline-flex rounded-full h-2 w-2 bg-amber-500"></span>
                </span>
              </div>
              <p className="text-[11px] text-amber-800">
                <span className="font-medium animate-pulse">Demo Version :</span> Currently, the same data is shown for both parents as all reports come from one phone number. In production, each parent will have their own phone number and separate health records.
              </p>
            </div>
          </CardContent>
        </Card>

        {showDatePickerModal && (
          <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
            <Card className="w-full max-w-md bg-white shadow-xl">
              <CardContent className="p-6">
                <div className="flex justify-between items-center mb-4">
                  <div className="flex items-center gap-2">
                    <Sparkles className={`w-5 h-5 ${selectedPerson === 'father' ? 'text-blue-600' : 'text-pink-600'}`} />
                    <h3 className={`text-lg font-bold ${selectedPerson === 'father' ? 'text-blue-900' : 'text-pink-900'}`}>AI Health Summary</h3>
                  </div>
                  <button
                    onClick={() => setShowDatePickerModal(false)}
                    className="text-slate-400 hover:text-slate-600"
                  >
                    <X className="w-5 h-5" />
                  </button>
                </div>

                <p className="text-sm text-slate-600 mb-4">
                  Select a date range to analyze health reports for {selectedPerson === 'father' ? 'Father' : 'Mother'}.
                </p>

                <div className="space-y-4">
                  <div>
                    <label className="block text-xs font-medium text-slate-700 mb-1">From Date</label>
                    <Input
                      type="date"
                      value={startDate}
                      onChange={(e) => setStartDate(e.target.value)}
                      className={`text-sm focus:ring-${selectedPerson === 'father' ? 'blue' : 'pink'}-500`}
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-medium text-slate-700 mb-1">To Date</label>
                    <Input
                      type="date"
                      value={endDate}
                      onChange={(e) => setEndDate(e.target.value)}
                      className={`text-sm focus:ring-${selectedPerson === 'father' ? 'blue' : 'pink'}-500`}
                    />
                  </div>

                  <div className="text-xs text-slate-500 bg-slate-50 p-2 rounded max-h-[150px] overflow-y-auto">
                    <p className="font-medium mb-1">💡 Reports in database:</p>
                    <ul className="list-disc list-inside">
                      {personFilteredReports.map((r, i) => (
                        <li key={i}>{new Date(r.createdAt).toLocaleDateString()} - {r.isCritical ? '⚠️ Critical' : '✓ Normal'}</li>
                      ))}
                    </ul>
                  </div>

                  <div className="flex gap-2 pt-2">
                    <Button
                      onClick={() => {
                        setStartDate('');
                        setEndDate('');
                      }}
                      variant="outline"
                      className="flex-1 text-sm"
                    >
                      Clear Dates
                    </Button>
                    <Button
                      onClick={generateAISummary}
                      disabled={isSummarizing}
                      className={`flex-1 bg-gradient-to-r ${currentTheme.gradient} text-white hover:opacity-90`}
                    >
                      {isSummarizing ? (
                        <>
                          <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                          Generating...
                        </>
                      ) : (
                        <>
                          <Sparkles className="w-4 h-4 mr-2" />
                          Generate Summary
                        </>
                      )}
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        )}

        {/* Email Modal */}
        {showEmailModal && (
          <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
            <Card className="w-full max-w-md bg-white shadow-xl">
              <CardContent className="p-6">
                <div className="flex justify-between items-center mb-4">
                  <div className="flex items-center gap-2">
                    <Mail className="w-5 h-5 text-blue-600" />
                    <h3 className={`text-lg font-bold ${selectedPerson === 'father' ? 'text-blue-900' : 'text-pink-900'}`}>Email to Doctor</h3>
                  </div>
                  <button
                    onClick={() => setShowEmailModal(false)}
                    className="text-slate-400 hover:text-slate-600"
                  >
                    <X className="w-5 h-5" />
                  </button>
                </div>

                <p className="text-sm text-slate-600 mb-4">
                  Send the AI health summary to your family doctor.
                </p>

                <div className="space-y-4">
                  <div>
                    <label className="block text-xs font-medium text-slate-700 mb-1">From Email (Your Email)</label>
                    <Input
                      type="email"
                      value={emailFrom}
                      onChange={(e) => setEmailFrom(e.target.value)}
                      placeholder="your.email@example.com"
                      className="text-sm"
                    />
                  </div>

                  <div>
                    <label className="block text-xs font-medium text-slate-700 mb-1">To Email (Doctor's Email)</label>
                    <Input
                      type="email"
                      value={emailTo}
                      onChange={(e) => setEmailTo(e.target.value)}
                      placeholder="doctor@clinic.com"
                      className="text-sm"
                    />
                  </div>

                  <div className="bg-slate-50 rounded-lg p-3 max-h-[200px] overflow-y-auto">
                    <p className="text-[10px] font-medium text-slate-500 mb-2">Email Preview:</p>
                    <p className="text-[11px] text-slate-600 whitespace-pre-wrap line-clamp-4">
                      Subject: Health Summary for {selectedPerson === 'father' ? 'Father' : 'Mother'} - Dear Comrade
                    </p>
                    <p className="text-[11px] text-slate-600 mt-2 line-clamp-3">
                      {aiSummary?.substring(0, 150)}...
                    </p>
                  </div>

                  <div className="flex gap-2 pt-2">
                    <Button
                      onClick={() => setShowEmailModal(false)}
                      variant="outline"
                      className="flex-1 text-sm"
                    >
                      Cancel
                    </Button>
                    <Button
                      onClick={sendEmailToDoctor}
                      className="flex-1 bg-gradient-to-r from-blue-500 to-blue-600 text-white hover:opacity-90"
                    >
                      <Mail className="w-4 h-4 mr-2" />
                      Send Email
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        )}

        {/* AI Summary Result - Single Big Scroll Area */}
        {showSummary && aiSummary && (
          <Card className={`bg-gradient-to-r ${selectedPerson === 'father' ? 'from-blue-50 to-blue-50/50' : 'from-pink-50 to-pink-50/50'} border ${currentTheme.border} shadow-lg overflow-hidden`}>
            <CardContent className="p-0">
              <div className={`flex justify-between items-center p-4 pb-2 sticky top-0 bg-gradient-to-r ${selectedPerson === 'father' ? 'from-blue-50 to-blue-50/50' : 'from-pink-50 to-pink-50/50'} z-10 border-b ${currentTheme.border}`}>
                <div className="flex items-center gap-2">
                  <Sparkles className={`w-5 h-5 ${selectedPerson === 'father' ? 'text-blue-600' : 'text-pink-600'}`} />
                  <h3 className={`text-base font-bold ${currentTheme.text}`}>AI Health Summary</h3>
                  <Badge className={`${currentTheme.accentLight} ${currentTheme.text} text-[10px] border ${currentTheme.border}`}>
                    Sarvam AI
                  </Badge>
                </div>
                <button
                  onClick={() => setShowSummary(false)}
                  className={`${selectedPerson === 'father' ? 'text-blue-400' : 'text-pink-400'} hover:${selectedPerson === 'father' ? 'text-blue-600' : 'text-pink-600'} transition-colors`}
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              <ScrollArea className="h-[550px]">
                <div className="p-4 space-y-4">
                  <div className="bg-white rounded-lg p-4 shadow-sm">
                    <div className="flex justify-between items-start mb-2">
                      <h4 className="text-lg font-bold text-slate-800">
                        {aiSummary.split('\n')[0]?.replace(/\*\*/g, '')}
                      </h4>
                      <Badge variant="outline" className="text-[10px]">
                        AI Generated
                      </Badge>
                    </div>
                    <div className="grid grid-cols-2 gap-3 mt-3">
                      <div className="bg-slate-50 rounded-lg p-2 text-center">
                        <p className="text-[10px] text-slate-500">Period</p>
                        <p className="text-xs font-semibold text-slate-700 break-words">
                          {(() => {
                            const match = aiSummary.match(/\*\*Period:\*\* (.*?)(?:\n|$)/);
                            return match ? match[1].replace(/\*\*/g, '') : 'N/A';
                          })()}
                        </p>
                      </div>
                      <div className="bg-slate-50 rounded-lg p-2 text-center">
                        <p className="text-[10px] text-slate-500">Reports Analyzed</p>
                        <p className="text-xs font-semibold text-slate-700">
                          {(() => {
                            const match = aiSummary.match(/\*\*Reports Analyzed:\*\* (.*?)(?:\n|$)/);
                            return match ? match[1].replace(/\*\*/g, '') : 'N/A';
                          })()}
                        </p>
                      </div>
                    </div>
                  </div>

                  {aiSummary.includes('CRITICAL ALERT') && (
                    <div className="bg-red-50 border-l-4 border-red-500 rounded-lg p-3">
                      <div className="flex items-center gap-2 mb-1">
                        <AlertTriangle className="w-4 h-4 text-red-500" />
                        <span className="text-xs font-bold text-red-700">Critical Alert Detected</span>
                      </div>
                      <p className="text-xs text-red-600 leading-relaxed">
                        {(() => {
                          const match = aiSummary.match(/⚠️ \*\*CRITICAL ALERT:\*\* (.*?)(?:\n|$)/);
                          return match ? match[1].replace(/\*\*/g, '') : 'Immediate medical attention required';
                        })()}
                      </p>
                    </div>
                  )}

                  <div className={`rounded-lg p-3 ${aiSummary.includes('Requires immediate medical attention') ? 'bg-red-50' : 'bg-emerald-50'}`}>
                    <div className="flex items-center gap-2 mb-1">
                      {aiSummary.includes('Requires immediate medical attention') ? (
                        <AlertTriangle className="w-4 h-4 text-red-500" />
                      ) : (
                        <CheckCircle2 className="w-4 h-4 text-emerald-500" />
                      )}
                      <span className="text-xs font-bold">Overall Health Status</span>
                    </div>
                    <p className="text-sm leading-relaxed">
                      {(() => {
                        const match = aiSummary.match(/✅ \*\*Overall Health Status:\*\* (.*?)(?:\n|$)/);
                        return match ? match[1].replace(/\*\*/g, '') : 'Status unknown';
                      })()}
                    </p>
                  </div>

                  <div className="bg-white rounded-lg p-3 shadow-sm">
                    <h5 className={`text-xs font-bold ${currentTheme.text} mb-2 flex items-center gap-2`}>
                      <Activity className="w-3 h-3" />
                      Key Observations
                    </h5>
                    <div className="space-y-2">
                      {(() => {
                        const observations = aiSummary.match(/📋 \*\*Key Observations:\*\*([\s\S]*?)(?=\n\n💡|\n\*\*|$)/);
                        if (observations && observations[1]) {
                          const lines = observations[1].split('\n').filter(l => l.trim() && !l.includes('**'));
                          return lines.map((line, idx) => (
                            <div key={idx} className="flex gap-2 text-xs text-slate-600">
                              <span className={`${selectedPerson === 'father' ? 'text-blue-500' : 'text-pink-500'} mt-0.5`}>•</span>
                              <span className="flex-1 leading-relaxed break-words">{line.replace(/[•]/g, '').trim()}</span>
                            </div>
                          ));
                        }
                        return <p className="text-xs text-slate-500">No observations available</p>;
                      })()}
                    </div>
                  </div>

                  {aiSummary.includes('critical alert') && (
                    <div className="bg-amber-50 rounded-lg p-3">
                      <h5 className="text-xs font-bold text-amber-800 mb-2 flex items-center gap-2">
                        <AlertTriangle className="w-3 h-3" />
                        Critical Details
                      </h5>
                      <div className="space-y-3">
                        {(() => {
                          const fullText = aiSummary;
                          const criticalItems = [];

                          const lines = fullText.split('\n');
                          let currentItem = '';
                          let inCriticalSection = false;

                          for (let i = 0; i < lines.length; i++) {
                            const line = lines[i];

                            if (line.match(/^\s*\d+\./)) {
                              if (currentItem) {
                                criticalItems.push(currentItem);
                              }
                              currentItem = line.trim();
                              inCriticalSection = true;
                            }
                            else if (inCriticalSection && line.trim() && !line.match(/^\s*\d+\./) && !line.includes('**Recommendations**') && !line.includes('💡')) {
                              currentItem += ' ' + line.trim();
                            }
                            else if (line.includes('**Recommendations**') || line.includes('💡')) {
                              if (currentItem) {
                                criticalItems.push(currentItem);
                                currentItem = '';
                              }
                              break;
                            }
                          }

                          if (currentItem) {
                            criticalItems.push(currentItem);
                          }

                          const cleanedItems = criticalItems.map(item => {
                            return item.replace(/^\d+\.\s*/, '').trim();
                          }).filter(item => item.length > 0);

                          return cleanedItems.map((item, idx) => (
                            <div key={idx} className="bg-white rounded-lg p-3 shadow-sm">
                              <div className="flex gap-2">
                                <span className="text-amber-600 font-bold text-sm">{idx + 1}.</span>
                                <p className="text-xs text-amber-800 leading-relaxed whitespace-normal break-words flex-1">
                                  {item}
                                </p>
                              </div>
                            </div>
                          ));
                        })()}
                      </div>
                    </div>
                  )}

                  <div className="bg-blue-50 rounded-lg p-3">
                    <h5 className="text-xs font-bold text-blue-800 mb-2 flex items-center gap-2">
                      <HeartPulse className="w-3 h-3" />
                      Recommendations
                    </h5>
                    <div className="space-y-2">
                      {(() => {
                        const recs = aiSummary.match(/💡 \*\*Recommendations:\*\*([\s\S]*?)(?=\n\n---|$)/);
                        if (recs && recs[1]) {
                          const lines = recs[1].split('\n').filter(l => l.trim() && l.includes('•'));
                          return lines.map((line, idx) => (
                            <div key={idx} className="flex gap-2 text-xs text-blue-700">
                              <span className="text-blue-500">✓</span>
                              <span className="flex-1 leading-relaxed break-words">{line.replace('•', '').trim()}</span>
                            </div>
                          ));
                        }
                        return <p className="text-xs text-slate-500">No recommendations available</p>;
                      })()}
                    </div>
                  </div>

                  {/* Email Button */}
                  <div className="flex gap-2 pt-2">
                    <Button
                      onClick={() => setShowEmailModal(true)}
                      className="flex items-center gap-2 text-xs font-bold px-3 py-1.5 rounded-lg bg-gradient-to-r from-blue-500 to-blue-600 text-white hover:opacity-90"
                    >
                      <Mail className="w-3 h-3" />
                      Email to Doctor
                    </Button>
                  </div>

                  <div className={`border-t ${currentTheme.border} pt-3`}>
                    <p className={`text-[9px] ${selectedPerson === 'father' ? 'text-blue-500' : 'text-pink-500'} italic`}>
                      🤖 Generated by Sarvam AI • Always consult with healthcare professionals for medical decisions
                    </p>
                  </div>
                </div>
              </ScrollArea>
            </CardContent>
          </Card>
        )}

        <section className="grid grid-cols-2 md:grid-cols-4 gap-3">
          <MetricCard
            title={`${selectedPerson === 'father' ? 'Father' : 'Mother'}'s Reports`}
            value={personFilteredReports.length}
            icon={<Phone className="w-4 h-4" />}
            onClick={() => setFilter('all')}
            active={filter === 'all'}
            activeColor={selectedPerson === 'father' ? 'blue' : 'pink'}
            theme={currentTheme}
          />
          <MetricCard
            title="Critical Alerts"
            value={criticalCount}
            icon={<AlertTriangle className="w-4 h-4" />}
            highlight={criticalCount > 0}
            onClick={() => setFilter('critical')}
            active={filter === 'critical'}
            activeColor="red"
            theme={currentTheme}
          />
          <MetricCard
            title="Normal Reports"
            value={normalCount}
            icon={<CheckCircle2 className="w-4 h-4" />}
            onClick={() => setFilter('normal')}
            active={filter === 'normal'}
            activeColor="green"
            theme={currentTheme}
          />
          <MetricCard
            title="All Reports"
            value={personFilteredReports.length}
            icon={<Activity className="w-4 h-4" />}
            onClick={() => setFilter('all')}
            active={filter === 'all'}
            activeColor={selectedPerson === 'father' ? 'blue' : 'pink'}
            theme={currentTheme}
          />
        </section>

        <Card className={`${currentTheme.cardBg} border ${currentTheme.border} shadow-sm overflow-hidden transition-all duration-500 ${chartAnimation ? 'scale-[1.01]' : 'scale-100'}`}>
          <CardContent className="p-4">
            <div className="flex justify-between items-center mb-3">
              <div>
                <h2 className={`text-sm font-bold ${currentTheme.text} flex items-center gap-2 transition-colors duration-300`}>
                  <TrendingUp className="w-4 h-4" />
                  {getChartTitle()}
                </h2>
              </div>
              <button
                onClick={() => setShowFullGraph(!showFullGraph)}
                className={`text-xs ${selectedPerson === 'father' ? 'text-blue-600' : 'text-pink-600'} hover:opacity-80 flex items-center gap-1`}
              >
                {showFullGraph ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />}
                {showFullGraph ? 'Compact' : 'Expand'}
              </button>
            </div>

            <div className={`transition-all duration-300 ${showFullGraph ? 'h-[350px]' : 'h-[200px]'}`}>
              {chartData.length > 0 ? (
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={chartData}>
                    <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                    <XAxis
                      dataKey="date"
                      stroke="#64748b"
                      fontSize={10}
                      tickLine={false}
                      interval={showFullGraph ? 0 : 'preserveStartEnd'}
                    />
                    <YAxis
                      stroke="#64748b"
                      fontSize={10}
                      tickLine={false}
                    />
                    <Tooltip
                      contentStyle={{
                        backgroundColor: 'white',
                        border: `1px solid ${filter === 'all' ? '#cbd5e1' : getChartColor()}`,
                        borderRadius: '8px',
                        fontSize: '11px',
                        padding: '6px 10px'
                      }}
                    />
                    <Legend wrapperStyle={{ fontSize: '11px' }} />

                    {filter === 'all' ? (
                      <>
                        <Bar
                          dataKey="critical"
                          fill="#ef4444"
                          name="Critical Alerts"
                          animationDuration={500}
                          animationBegin={0}
                          radius={[4, 4, 0, 0]}
                        />
                        <Bar
                          dataKey="normal"
                          fill="#10b981"
                          name="Normal Reports"
                          animationDuration={500}
                          animationBegin={150}
                          radius={[4, 4, 0, 0]}
                        />
                      </>
                    ) : filter === 'critical' ? (
                      <Bar
                        dataKey="critical"
                        fill={getChartColor()}
                        name="Critical Alerts"
                        animationDuration={500}
                        animationBegin={0}
                        radius={[4, 4, 0, 0]}
                      />
                    ) : (
                      <Bar
                        dataKey="normal"
                        fill={getChartColor()}
                        name="Normal Reports"
                        animationDuration={500}
                        animationBegin={0}
                        radius={[4, 4, 0, 0]}
                      />
                    )}
                  </BarChart>
                </ResponsiveContainer>
              ) : (
                <div className="flex items-center justify-center h-full text-slate-400 text-sm">
                  No data available
                </div>
              )}
            </div>

            <div className="mt-2 pt-2 border-t border-slate-100">
              <div className="flex justify-between items-center text-[10px] text-slate-500">
                <div className="flex items-center gap-3">
                  <span>Peak: {Math.max(...chartData.map(d =>
                    filter === 'critical' ? d.critical :
                      filter === 'normal' ? d.normal :
                        d.total
                  ), 0)}</span>
                  <span>Total: {chartData.reduce((sum, d) => sum + (filter === 'critical' ? d.critical : filter === 'normal' ? d.normal : d.total), 0)}</span>
                </div>
                <div className="flex items-center gap-1">
                  <Calendar className="w-3 h-3" />
                  <span>{chartData[0]?.date || 'No data'} - {chartData[chartData.length - 1]?.date || 'No data'}</span>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        <div className="flex flex-col sm:flex-row gap-2 items-stretch sm:items-center justify-between">
          <div className="relative flex-1 max-w-md">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-3 h-3 text-slate-400" />
            <Input
              type="text"
              placeholder="Search reports..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className={`pl-8 pr-8 py-1.5 text-sm bg-white border ${currentTheme.border} focus:border-${selectedPerson === 'father' ? 'blue' : 'pink'}-500 focus:ring-${selectedPerson === 'father' ? 'blue' : 'pink'}-500`}
            />
            {searchTerm && (
              <button
                onClick={() => setSearchTerm('')}
                className="absolute right-3 top-1/2 transform -translate-y-1/2"
              >
                <X className="w-3 h-3 text-slate-400 hover:text-slate-600" />
              </button>
            )}
          </div>

          {(filter !== 'all' || searchTerm) && (
            <div className="flex items-center gap-2 flex-wrap">
              <span className="text-[10px] text-slate-500">Active:</span>
              {filter !== 'all' && (
                <Badge
                  variant="secondary"
                  className={`cursor-pointer text-xs py-0 px-2 ${filter === 'critical' ? 'bg-red-100 text-red-700' : 'bg-emerald-100 text-emerald-700'}`}
                  onClick={() => setFilter('all')}
                >
                  {filter === 'critical' ? '⚠️ Critical' : '✓ Normal'}
                  <X className="w-2 h-2 ml-1" />
                </Badge>
              )}
              {searchTerm && (
                <Badge
                  variant="secondary"
                  className="cursor-pointer bg-slate-100 text-slate-700 text-xs py-0 px-2"
                  onClick={() => setSearchTerm('')}
                >
                  "{searchTerm.substring(0, 15)}"
                  <X className="w-2 h-2 ml-1" />
                </Badge>
              )}
              <button
                onClick={clearFilters}
                className={`text-[10px] ${selectedPerson === 'father' ? 'text-blue-600' : 'text-pink-600'} hover:opacity-80 font-medium`}
              >
                Clear all
              </button>
            </div>
          )}
        </div>

        <div className="space-y-2">
          <div className="flex justify-between items-center">
            <h3 className={`text-xs font-semibold ${currentTheme.text} transition-colors duration-300`}>
              {selectedPerson === 'father' ? 'Father' : 'Mother'}'s Reports ({filteredReports.length})
            </h3>
          </div>

          <ScrollArea className="h-[35vh] rounded-xl border border-slate-200 bg-white shadow-sm">
            <div className="space-y-2 p-3">
              {filteredReports.length === 0 ? (
                <div className="text-center py-8">
                  <div className="inline-flex items-center justify-center w-10 h-10 rounded-full bg-slate-100 mb-2">
                    {filter === 'critical' ? <AlertTriangle className="w-5 h-5 text-slate-400" /> : <CheckCircle2 className="w-5 h-5 text-slate-400" />}
                  </div>
                  <p className="text-slate-500 text-sm">No reports found</p>
                  <button
                    onClick={clearFilters}
                    className="mt-2 text-xs text-emerald-600 hover:text-emerald-700 font-medium"
                  >
                    Clear filters
                  </button>
                </div>
              ) : (
                filteredReports.map((report) => (
                  <div key={report.id} className={`p-3 rounded-lg border transition-all duration-200 hover:shadow-sm ${report.isCritical ? "bg-gradient-to-r from-red-50 to-red-50/50 border-red-200" : `${currentTheme.accentLight} border-slate-100`}`}>
                    <div className="flex justify-between items-start gap-2">
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 mb-1 flex-wrap">
                          <Badge variant={report.isCritical ? "destructive" : "secondary"} className={report.isCritical ? "bg-red-600 text-white text-[9px] px-1.5 py-0" : `text-[9px] px-1.5 py-0 ${currentTheme.text}`}>
                            {report.isCritical ? "CRITICAL" : "NORMAL"}
                          </Badge>
                          <span className="text-[9px] font-medium text-slate-400">
                            {new Date(report.createdAt).toLocaleString()}
                          </span>
                        </div>
                        <p className="text-slate-800 text-xs leading-relaxed line-clamp-2">{report.summary}</p>
                      </div>
                    </div>
                  </div>
                ))
              )}
            </div>
          </ScrollArea>
        </div>
      </div>
    </div>
  );
}

function MetricCard({ title, value, icon, highlight, onClick, active, activeColor, theme }: any) {
  const getActiveStyles = () => {
    if (!active) return "bg-white border-slate-200";

    switch (activeColor) {
      case 'red': return 'bg-gradient-to-br from-red-500 to-red-600 border-red-600 text-white shadow-md shadow-red-500/20 scale-105';
      case 'green': return 'bg-gradient-to-br from-emerald-500 to-emerald-600 border-emerald-600 text-white shadow-md shadow-emerald-500/20 scale-105';
      case 'blue': return 'bg-gradient-to-br from-blue-500 to-blue-600 border-blue-600 text-white shadow-md shadow-blue-500/20 scale-105';
      case 'pink': return 'bg-gradient-to-br from-pink-500 to-pink-600 border-pink-600 text-white shadow-md shadow-pink-500/20 scale-105';
      default: return 'bg-slate-800 border-slate-800 text-white';
    }
  };

  return (
    <Card
      className={`border shadow-sm transition-all duration-300 cursor-pointer hover:shadow-md ${getActiveStyles()}`}
      onClick={onClick}
    >
      <CardContent className="p-3 flex items-center justify-between">
        <div>
          <p className={`text-[8px] font-bold uppercase ${active ? "text-white/80" : "text-slate-400"}`}>
            {title}
          </p>
          <h3 className={`text-lg font-black ${active ? "text-white" : highlight ? "text-red-600" : "text-slate-800"}`}>
            {value}
          </h3>
        </div>
        <div className={`p-1.5 rounded-lg transition-all duration-200 ${active ? "bg-white/20" : theme?.accentLight || "bg-slate-100"}`}>
          {active ? (
            <div className="text-white">{icon}</div>
          ) : (
            icon
          )}
        </div>
      </CardContent>
    </Card>
  );
}